# Generated by Django 4.2.8 on 2026-04-12 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_hlv_id_taikhoan_alter_hoivien_id_hlv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hlv',
            name='Id_TaiKhoan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hoivien',
            name='Id_HLV',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hlv'),
        ),
        migrations.AlterField(
            model_name='hoivien',
            name='Id_TaiKhoan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
