# Generated by Django 4.2.8 on 2026-04-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThuTuNgayTap', models.CharField(max_length=20)),
                ('Id_HoiVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hoivien')),
            ],
        ),
        migrations.CreateModel(
            name='BuaAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenBua', models.CharField(max_length=20)),
                ('Id_HoiVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hoivien')),
            ],
        ),
        migrations.CreateModel(
            name='LichTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThuTrongTuan', models.SmallIntegerField()),
                ('GioBatDau', models.TimeField()),
                ('GioKetThuc', models.TimeField()),
                ('Id_HoiVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hoivien')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietBuaAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenThucPham', models.CharField(max_length=100)),
                ('Luong', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Calo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Protein', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Carb', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Fat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Id_LichAn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.buaan')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietBaiTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MucLuc', models.CharField(blank=True, max_length=20, null=True)),
                ('TenBai', models.CharField(max_length=255)),
                ('ThoiGian', models.CharField(blank=True, max_length=50, null=True)),
                ('SoLan', models.IntegerField(blank=True, null=True)),
                ('SoHiep', models.IntegerField(blank=True, null=True)),
                ('Nghi', models.CharField(blank=True, max_length=50, null=True)),
                ('CuongDo', models.CharField(blank=True, max_length=20, null=True)),
                ('Id_BaiTap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.baitap')),
            ],
        ),
        migrations.CreateModel(
            name='ChiSoCoThe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CanNang', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ChieuCao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('VongBung', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('VongMong', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('BMI', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('PhanTramMo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('PhanTramCo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('TyLeTraoDoiChat', models.IntegerField(blank=True, null=True)),
                ('NgayTao', models.DateField(auto_now_add=True)),
                ('Id_HoiVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hoivien')),
            ],
        ),
    ]
