# Generated by Django 4.2.8 on 2026-04-12 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_hlv_id_taikhoan_alter_hoivien_id_hlv_and_more'),
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baitap',
            name='Id_HoiVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.hoivien'),
        ),
        migrations.AlterField(
            model_name='buaan',
            name='Id_HoiVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.hoivien'),
        ),
        migrations.AlterField(
            model_name='chisocothe',
            name='Id_HoiVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.hoivien'),
        ),
        migrations.AlterField(
            model_name='chitietbaitap',
            name='Id_BaiTap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.baitap'),
        ),
        migrations.AlterField(
            model_name='chitietbuaan',
            name='Id_LichAn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.buaan'),
        ),
        migrations.AlterField(
            model_name='lichtap',
            name='Id_HoiVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.hoivien'),
        ),
    ]
