# Generated by Django 4.2.8 on 2026-04-12 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiDang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TieuDe', models.CharField(max_length=255)),
                ('NoiDung', models.CharField(max_length=2000)),
                ('ThoiGianDang', models.DateTimeField(auto_now_add=True)),
                ('anhURL', models.CharField(blank=True, max_length=500, null=True)),
                ('Id_NguoiDang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TieuDe', models.CharField(max_length=255)),
                ('NoiDung', models.CharField(max_length=2000)),
                ('LoaiThongBao', models.CharField(blank=True, max_length=50, null=True)),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TuongTac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_BaiDang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.baidang')),
                ('Id_NguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TinNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoiDung', models.CharField(max_length=500)),
                ('ThoiGianGui', models.DateTimeField(auto_now_add=True)),
                ('DaXem', models.BooleanField(default=False)),
                ('Id_NguoiGui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan_gui', to=settings.AUTH_USER_MODEL)),
                ('Id_NguoiNhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan_nhan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DaXem', models.BooleanField(default=False)),
                ('Id_NguoiNhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Id_ThongBao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.thongbao')),
            ],
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoiDung', models.CharField(max_length=1000)),
                ('ThoiGianBinhLuan', models.DateTimeField(auto_now_add=True)),
                ('Id_BaiDang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.baidang')),
                ('Id_NguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
