# Generated by Django 4.2.8 on 2026-04-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baidang',
            name='TieuDe',
        ),
        migrations.AlterField(
            model_name='baidang',
            name='anhURL',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
