# Generated by Django 4.2.8 on 2026-04-12 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0002_remove_baidang_tieude_alter_baidang_anhurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baidang',
            name='Id_NguoiDang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='binhluan',
            name='Id_BaiDang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='social.baidang'),
        ),
        migrations.AlterField(
            model_name='binhluan',
            name='Id_NguoiDung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chitietthongbao',
            name='Id_NguoiNhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chitietthongbao',
            name='Id_ThongBao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='social.thongbao'),
        ),
        migrations.AlterField(
            model_name='tinnhan',
            name='Id_NguoiGui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tin_nhan_gui', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tinnhan',
            name='Id_NguoiNhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tin_nhan_nhan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tuongtac',
            name='Id_BaiDang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='social.baidang'),
        ),
        migrations.AlterField(
            model_name='tuongtac',
            name='Id_NguoiDung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
